version: "3.8"

services:
  echonet_api:
    build: ./app
    container_name: echonet_api
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_TOKEN=${API_TOKEN}
    restart: unless-stopped
